// Habitat game types — mirrors backend models.py

export interface RegionData {
  id: number;
  name: string;
  x_size: number;
  y_size: number;
  terrain_type: number;
  lighting: number;
  neighbors: { west: number; east: number; north: number; south: number };
}

export interface GameObjectData {
  noid: number;
  class_id: number;
  x: number;
  y: number;
  orientation: number;
  gr_state: number;
  container_noid: number;
  style: number;
  extra: Record<string, any>;
}

export interface AvatarData {
  noid: number;
  name: string;
  x: number;
  y: number;
  orientation?: number;
  activity?: number;
  health: number;
  tokens: number;
  bank_account?: number;
}

export interface ChatMessage {
  name: string;
  text: string;
  time: number;
}

// PL/I class IDs — all 107+ original classes
export const ClassID = {
  REGION: 0,
  AVATAR: 1,
  AMULET: 2,
  GHOST: 3,
  ATM: 4,
  GAME_PIECE: 5,
  BAG: 6,
  BALL: 7,
  BOOK: 10,
  BOOMERANG: 11,
  BOTTLE: 12,
  BOX: 13,
  CLUB: 16,
  COMPASS: 17,
  COUNTERTOP: 18,
  CRYSTAL_BALL: 20,
  DIE: 21,
  DISPLAY_CASE: 22,
  DOOR: 23,
  DROPBOX: 24,
  DRUGS: 25,
  ESCAPE_DEV: 26,
  FAKE_GUN: 27,
  ELEVATOR: 28,
  FLAG: 29,
  FLASHLIGHT: 30,
  FRISBEE: 31,
  GARBAGE_CAN: 32,
  GROUND: 33,
  GUN: 34,
  GRENADE: 35,
  HAND_OF_GOD: 38,
  HAT: 39,
  INSTANT_OBJECT: 40,
  JACKET: 41,
  KEY: 42,
  KNICK_KNACK: 43,
  KNIFE: 44,
  MAGIC_LAMP: 45,
  MAGIC_STAFF: 46,
  MAGIC_WAND: 47,
  MAILBOX: 48,
  MATCHBOOK: 49,
  MOVIE_CAMERA: 52,
  PAPER: 54,
  PLAQUE: 55,
  SHORT_SIGN: 56,
  SIGN: 57,
  PLANT: 58,
  RING: 60,
  ROCK: 61,
  SECURITY_DEV: 63,
  SENSOR: 64,
  SIGN_OLD: 65,
  SKATEBOARD: 67,
  SKY: 69,
  STREET: 70,
  TAPE: 71,
  TELEPORT: 74,
  TICKET: 75,
  TOKENS: 76,
  WALL: 80,
  WINDUP_TOY: 82,
  CHANGOMATIC: 84,
  VENDO_FRONT: 85,
  VENDO_INSIDE: 86,
  TRAPEZOID: 87,
  HOLE: 88,
  SHOVEL: 89,
  SEX_CHANGER: 90,
  STUN_GUN: 91,
  SUPER_TRAPEZOID: 92,
  FLAT: 93,
  SPRAY_CAN: 95,
  PAWN_MACHINE: 96,
  SWITCH: 97,
  GLUE: 98,
  HEAD: 127,
  AQUARIUM: 129,
  BED: 130,
  BRIDGE: 131,
  BUILDING: 132,
  BUSH: 133,
  CHAIR: 134,
  CHEST: 135,
  COKE_MACHINE: 136,
  COUCH: 137,
  FENCE: 138,
  FLOOR_LAMP: 139,
  FORTUNE_MACHINE: 140,
  FOUNTAIN: 141,
  HOUSE_CAT: 143,
  HOT_TUB: 144,
  JUKEBOX: 145,
  POND: 147,
  RIVER: 148,
  ROOF: 149,
  SAFE: 150,
  PICTURE: 152,
  STEREO: 153,
  STREETLAMP: 154,
  TABLE: 155,
  TREE: 156,
  WINDOW: 157,
  BUREAUCRAT: 158,
  SHIRT: 159,
  PANTS: 160,
  GEMSTONE: 161,
} as const;

export const CLASS_NAMES: Record<number, string> = {
  [ClassID.REGION]: "Region",
  [ClassID.AVATAR]: "Avatar",
  [ClassID.AMULET]: "Amulet",
  [ClassID.GHOST]: "Ghost",
  [ClassID.ATM]: "ATM",
  [ClassID.GAME_PIECE]: "Game Piece",
  [ClassID.BAG]: "Bag",
  [ClassID.BALL]: "Ball",
  [ClassID.BOOK]: "Book",
  [ClassID.BOOMERANG]: "Boomerang",
  [ClassID.BOTTLE]: "Bottle",
  [ClassID.BOX]: "Box",
  [ClassID.CLUB]: "Club",
  [ClassID.COMPASS]: "Compass",
  [ClassID.COUNTERTOP]: "Countertop",
  [ClassID.CRYSTAL_BALL]: "Crystal Ball",
  [ClassID.DIE]: "Die",
  [ClassID.DISPLAY_CASE]: "Display Case",
  [ClassID.DOOR]: "Door",
  [ClassID.DROPBOX]: "Dropbox",
  [ClassID.DRUGS]: "Drugs",
  [ClassID.ESCAPE_DEV]: "Escape Device",
  [ClassID.FAKE_GUN]: "Fake Gun",
  [ClassID.ELEVATOR]: "Elevator",
  [ClassID.FLAG]: "Flag",
  [ClassID.FLASHLIGHT]: "Flashlight",
  [ClassID.FRISBEE]: "Frisbee",
  [ClassID.GARBAGE_CAN]: "Garbage Can",
  [ClassID.GROUND]: "Ground",
  [ClassID.GUN]: "Gun",
  [ClassID.GRENADE]: "Grenade",
  [ClassID.HAND_OF_GOD]: "Hand of God",
  [ClassID.HAT]: "Hat",
  [ClassID.INSTANT_OBJECT]: "Instant Object",
  [ClassID.JACKET]: "Jacket",
  [ClassID.KEY]: "Key",
  [ClassID.KNICK_KNACK]: "Knick-Knack",
  [ClassID.KNIFE]: "Knife",
  [ClassID.MAGIC_LAMP]: "Magic Lamp",
  [ClassID.MAGIC_STAFF]: "Magic Staff",
  [ClassID.MAGIC_WAND]: "Magic Wand",
  [ClassID.MAILBOX]: "Mailbox",
  [ClassID.MATCHBOOK]: "Matchbook",
  [ClassID.MOVIE_CAMERA]: "Movie Camera",
  [ClassID.PAPER]: "Paper",
  [ClassID.PLAQUE]: "Plaque",
  [ClassID.SHORT_SIGN]: "Short Sign",
  [ClassID.SIGN]: "Sign",
  [ClassID.SIGN_OLD]: "Sign",
  [ClassID.PLANT]: "Plant",
  [ClassID.RING]: "Ring",
  [ClassID.ROCK]: "Rock",
  [ClassID.SECURITY_DEV]: "Security Device",
  [ClassID.SENSOR]: "Sensor",
  [ClassID.SKATEBOARD]: "Skateboard",
  [ClassID.SKY]: "Sky",
  [ClassID.STREET]: "Street",
  [ClassID.TAPE]: "Tape",
  [ClassID.TELEPORT]: "Teleport",
  [ClassID.TICKET]: "Ticket",
  [ClassID.TOKENS]: "Tokens",
  [ClassID.WALL]: "Wall",
  [ClassID.WINDUP_TOY]: "Windup Toy",
  [ClassID.CHANGOMATIC]: "Chang-O-Matic",
  [ClassID.VENDO_FRONT]: "Vendo",
  [ClassID.VENDO_INSIDE]: "Vendo Inside",
  [ClassID.TRAPEZOID]: "Trapezoid",
  [ClassID.HOLE]: "Hole",
  [ClassID.SHOVEL]: "Shovel",
  [ClassID.SEX_CHANGER]: "Sex Changer",
  [ClassID.STUN_GUN]: "Stun Gun",
  [ClassID.SUPER_TRAPEZOID]: "Super Trapezoid",
  [ClassID.FLAT]: "Flat",
  [ClassID.SPRAY_CAN]: "Spray Can",
  [ClassID.PAWN_MACHINE]: "Pawn Machine",
  [ClassID.SWITCH]: "Switch",
  [ClassID.GLUE]: "Glue",
  [ClassID.HEAD]: "Head",
  [ClassID.AQUARIUM]: "Aquarium",
  [ClassID.BED]: "Bed",
  [ClassID.BRIDGE]: "Bridge",
  [ClassID.BUILDING]: "Building",
  [ClassID.BUSH]: "Bush",
  [ClassID.CHAIR]: "Chair",
  [ClassID.CHEST]: "Chest",
  [ClassID.COKE_MACHINE]: "Coke Machine",
  [ClassID.COUCH]: "Couch",
  [ClassID.FENCE]: "Fence",
  [ClassID.FLOOR_LAMP]: "Floor Lamp",
  [ClassID.FORTUNE_MACHINE]: "Fortune Machine",
  [ClassID.FOUNTAIN]: "Fountain",
  [ClassID.HOUSE_CAT]: "House Cat",
  [ClassID.HOT_TUB]: "Hot Tub",
  [ClassID.JUKEBOX]: "Jukebox",
  [ClassID.POND]: "Pond",
  [ClassID.RIVER]: "River",
  [ClassID.ROOF]: "Roof",
  [ClassID.SAFE]: "Safe",
  [ClassID.PICTURE]: "Picture",
  [ClassID.STEREO]: "Stereo",
  [ClassID.STREETLAMP]: "Streetlamp",
  [ClassID.TABLE]: "Table",
  [ClassID.TREE]: "Tree",
  [ClassID.WINDOW]: "Window",
  [ClassID.BUREAUCRAT]: "Bureaucrat",
  [ClassID.SHIRT]: "Shirt",
  [ClassID.PANTS]: "Pants",
  [ClassID.GEMSTONE]: "Gemstone",
};

// Object visual representation (retro ASCII style)
export const CLASS_SPRITES: Record<number, { char: string; color: string }> = {
  // Core
  [ClassID.AVATAR]: { char: "@", color: "#00ff00" },
  [ClassID.ATM]: { char: "$", color: "#ffff00" },
  [ClassID.DOOR]: { char: "+", color: "#c07020" },
  [ClassID.SIGN]: { char: "!", color: "#ffaa00" },
  [ClassID.SIGN_OLD]: { char: "!", color: "#ffaa00" },
  [ClassID.SHORT_SIGN]: { char: "!", color: "#ffaa00" },
  [ClassID.PLAQUE]: { char: "!", color: "#cc8844" },
  [ClassID.MAILBOX]: { char: "M", color: "#4488ff" },
  [ClassID.TELEPORT]: { char: "T", color: "#ff00ff" },
  [ClassID.VENDO_FRONT]: { char: "V", color: "#00cccc" },
  [ClassID.VENDO_INSIDE]: { char: "V", color: "#00cccc" },
  [ClassID.TOKENS]: { char: "*", color: "#ffff00" },
  [ClassID.GUN]: { char: "}", color: "#ff4444" },
  [ClassID.BAG]: { char: "b", color: "#c8a060" },
  [ClassID.KEY]: { char: "~", color: "#ffcc00" },
  [ClassID.PAPER]: { char: "?", color: "#ffffff" },
  [ClassID.GROUND]: { char: ".", color: "#404040" },
  [ClassID.STREET]: { char: "#", color: "#666666" },
  // Nature
  [ClassID.TREE]: { char: "T", color: "#228822" },
  [ClassID.BUSH]: { char: "w", color: "#22aa22" },
  [ClassID.PLANT]: { char: "f", color: "#33cc33" },
  [ClassID.ROCK]: { char: "o", color: "#888888" },
  [ClassID.RIVER]: { char: "~", color: "#2266ff" },
  [ClassID.POND]: { char: "~", color: "#4488ff" },
  [ClassID.FOUNTAIN]: { char: "Y", color: "#66aaff" },
  [ClassID.SKY]: { char: " ", color: "#1a0a30" },
  // Structure
  [ClassID.WALL]: { char: "#", color: "#555555" },
  [ClassID.FENCE]: { char: "|", color: "#886644" },
  [ClassID.BRIDGE]: { char: "=", color: "#aa8844" },
  [ClassID.BUILDING]: { char: "B", color: "#666688" },
  [ClassID.WINDOW]: { char: "O", color: "#6688aa" },
  [ClassID.ROOF]: { char: "^", color: "#884444" },
  [ClassID.ELEVATOR]: { char: "E", color: "#888888" },
  [ClassID.STREETLAMP]: { char: "I", color: "#ffff88" },
  // Furniture
  [ClassID.BED]: { char: "=", color: "#8866aa" },
  [ClassID.CHAIR]: { char: "h", color: "#886644" },
  [ClassID.COUCH]: { char: "=", color: "#aa6644" },
  [ClassID.TABLE]: { char: "_", color: "#886644" },
  [ClassID.COUNTERTOP]: { char: "_", color: "#888888" },
  [ClassID.FLOOR_LAMP]: { char: "i", color: "#ffff88" },
  [ClassID.AQUARIUM]: { char: "n", color: "#44aaff" },
  [ClassID.HOT_TUB]: { char: "U", color: "#4488ff" },
  [ClassID.JUKEBOX]: { char: "J", color: "#ff44ff" },
  [ClassID.STEREO]: { char: "S", color: "#ff44aa" },
  [ClassID.PICTURE]: { char: "P", color: "#cc88ff" },
  [ClassID.FLAG]: { char: "F", color: "#ff2222" },
  [ClassID.KNICK_KNACK]: { char: "k", color: "#ccaa88" },
  // Weapons
  [ClassID.KNIFE]: { char: "/", color: "#cccccc" },
  [ClassID.CLUB]: { char: "!", color: "#886644" },
  [ClassID.BOOMERANG]: { char: ")", color: "#cc8844" },
  [ClassID.STUN_GUN]: { char: "}", color: "#ffff44" },
  [ClassID.FAKE_GUN]: { char: "}", color: "#888888" },
  [ClassID.GRENADE]: { char: "0", color: "#44aa44" },
  // Magic
  [ClassID.AMULET]: { char: '"', color: "#ff44ff" },
  [ClassID.RING]: { char: "=", color: "#ffcc44" },
  [ClassID.CRYSTAL_BALL]: { char: "0", color: "#aa88ff" },
  [ClassID.MAGIC_LAMP]: { char: "L", color: "#ffaa44" },
  [ClassID.MAGIC_STAFF]: { char: "/", color: "#aa44ff" },
  [ClassID.MAGIC_WAND]: { char: "-", color: "#ff44ff" },
  [ClassID.GEMSTONE]: { char: "*", color: "#44ffaa" },
  // Containers
  [ClassID.BOX]: { char: "[", color: "#886644" },
  [ClassID.CHEST]: { char: "[", color: "#ccaa44" },
  [ClassID.SAFE]: { char: "[", color: "#888888" },
  [ClassID.DISPLAY_CASE]: { char: "[", color: "#aaaacc" },
  [ClassID.GARBAGE_CAN]: { char: "U", color: "#666666" },
  [ClassID.DROPBOX]: { char: "D", color: "#4466aa" },
  // Wearable
  [ClassID.HAT]: { char: "^", color: "#cc6644" },
  [ClassID.JACKET]: { char: "J", color: "#4466aa" },
  [ClassID.SHIRT]: { char: "t", color: "#44aaaa" },
  [ClassID.PANTS]: { char: "n", color: "#4444aa" },
  [ClassID.HEAD]: { char: "O", color: "#ffcc88" },
  // Machines
  [ClassID.COKE_MACHINE]: { char: "C", color: "#ff2222" },
  [ClassID.FORTUNE_MACHINE]: { char: "?", color: "#ffaa44" },
  [ClassID.PAWN_MACHINE]: { char: "P", color: "#ccaa44" },
  [ClassID.CHANGOMATIC]: { char: "X", color: "#44ffff" },
  [ClassID.SWITCH]: { char: "s", color: "#aaaaaa" },
  // Creatures
  [ClassID.GHOST]: { char: "G", color: "#aaaaff" },
  [ClassID.HOUSE_CAT]: { char: "c", color: "#ffaa44" },
  [ClassID.BUREAUCRAT]: { char: "B", color: "#888888" },
  // Portable items
  [ClassID.FLASHLIGHT]: { char: "!", color: "#ffff44" },
  [ClassID.SHOVEL]: { char: "\\", color: "#886644" },
  [ClassID.COMPASS]: { char: "+", color: "#44aaaa" },
  [ClassID.TAPE]: { char: "o", color: "#888888" },
  [ClassID.GLUE]: { char: "o", color: "#ffffff" },
  [ClassID.SPRAY_CAN]: { char: "!", color: "#44aa44" },
  [ClassID.MATCHBOOK]: { char: "m", color: "#ff6644" },
  [ClassID.BOTTLE]: { char: "!", color: "#44aaaa" },
  [ClassID.DRUGS]: { char: "+", color: "#ff44ff" },
  [ClassID.SKATEBOARD]: { char: "_", color: "#cc8844" },
  [ClassID.FRISBEE]: { char: "o", color: "#44ff44" },
  [ClassID.BALL]: { char: "o", color: "#ff4444" },
  [ClassID.WINDUP_TOY]: { char: "t", color: "#ffaa44" },
  [ClassID.MOVIE_CAMERA]: { char: "c", color: "#888888" },
  [ClassID.TICKET]: { char: "t", color: "#ffff88" },
  [ClassID.GAME_PIECE]: { char: "p", color: "#ff8844" },
  [ClassID.DIE]: { char: "d", color: "#ffffff" },
  [ClassID.BOOK]: { char: "B", color: "#884422" },
  // Special
  [ClassID.HAND_OF_GOD]: { char: "H", color: "#ffffff" },
  [ClassID.SEX_CHANGER]: { char: "X", color: "#ff88ff" },
  [ClassID.HOLE]: { char: "O", color: "#222222" },
  [ClassID.ESCAPE_DEV]: { char: "e", color: "#44ffaa" },
  [ClassID.INSTANT_OBJECT]: { char: "?", color: "#ffff44" },
  [ClassID.SENSOR]: { char: "s", color: "#44ff44" },
  [ClassID.SECURITY_DEV]: { char: "!", color: "#ff4444" },
  // Geometry
  [ClassID.FLAT]: { char: "-", color: "#666666" },
  [ClassID.TRAPEZOID]: { char: "/", color: "#666666" },
  [ClassID.SUPER_TRAPEZOID]: { char: "/", color: "#888888" },
};
