"""Extract the 90 fortune strings from class_fortune_machine.pl1 into
backend/fortunes_data.py (mechanical conversion; PL/I '' -> ')."""
import re
import sys
from pathlib import Path

SRC = Path(sys.argv[1])
OUT = Path(__file__).resolve().parent.parent / "backend" / "fortunes_data.py"

text = SRC.read_text(encoding="latin-1")
m = re.search(r"significant_messages\(0:LAST_MSG\).*?init\((.*?)\);\s*\n\s*success",
              text, re.S)
body = m.group(1)
items = re.findall(r"'((?:[^']|'')*)'\s*(?:,|\s*$)", body, re.M)
msgs = [i.replace("''", "'") for i in items]
last = int(re.search(r"LAST_MSG by (\d+)", text).group(1))
assert len(msgs) == last + 1, (len(msgs), last)
lines = ['"""Generated by tools/extract_fortunes.py from class_fortune_machine.pl1.',
         'Do not edit by hand."""', "", "FORTUNES = ["]
lines += [f"    {m!r}," for m in msgs]
lines += ["]", "", f"LAST_MSG = {last}", ""]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(len(msgs), "fortunes ->", OUT)
